spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: claimant
  autoconfigure:
    exclude:
            org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

message: This is prod enviornment
