server:
  undertow:
    io-threads: 15
    worker-threads: 150
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
   