spring:
  pid:
    file: helloworld.pid
eureka:
  instance:
    hostname: helloworld
hystrix:
  command:
    getClaimant:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 60000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 4
        sleepWindowInMilliseconds: 60000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  stream:
    queue:
      send-id: false

ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000