spring:
  pid:
    file: claimantservice.pid
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
  instance:
    hostname: claimantservice
hystrix:
  stream:
    queue:
      send-id: false